---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          image: docker.io/iejalapeno/topology@sha256:90c9fc29eaf7576f4deb6d89baa9a6990e44931be23393a7786536a2771e6fce
          imagePullPolicy: Always
          name: topology
metadata:
  name: topology
  namespace: jalapeno
