---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: topology
spec:
  replicas: 1
  selector:
    matchLabels:
      app: topology
  template:
    metadata:
      labels:
        app: topology
    spec:
      containers:
        - args:
          - --v
          - "5"
          - --message-server
          - "broker.jalapeno:9092"
          - --database-server
          - "http://arangodb.jalapeno:8529"
          - --database-name
          - "jalapeno"
          - --database-user
          - "root"
          - --database-pass
          - "jalapeno"
          image: docker.io/iejalapeno/topology@sha256:0c93ce1822171229a3063b355bb9e56d5f7d6b8f707c11c5a45b4d52f3a49547
          imagePullPolicy: Always
          name: topology
metadata:
  name: topology
  namespace: jalapeno
